### ISSUE TITLE
Outdated Release

### ISSUE THREAD

**Issue by ShalokShalom** [DISTRHO/Website#1]
Hi :)

Thanks for your works.
It would be a neat idea, to also let others know, that this project is alive and well.

The website currently tells everybody, that 2018 was the last release, despite a good dozen repos here being updated almost daily.

That seems very unfortunate, since it leaves the taste of an unmaintained project, which reduced community contributions, adoption rate by distros and similar things for years now.

Is there nobody responsible for that?

**Comment by falkTX** [comment]
website work is just super boring while there is more interesting stuff to do.

not to mention there also being more critical components to handle first.
For example, right now Carla needs a bugfix release and JACK also needs some fixes for regressions on the example tools and macOS no longer working.

website will be updated in due time, but as long as there are more important/critical things to do, it will get sidelined.

**Comment by ShalokShalom** [comment]
I think this is a horrible mindset. You could just release a simple blog post that reads "We are still alive, project is maintained, this is what we are currently working on."

There are always "more important things to do"
